In [44]:
import numpy as np

In [45]:
?np.array

In [46]:
liste1=[1,2,3,4,5,6]
print(liste1)

[1, 2, 3, 4, 5, 6]


In [47]:
ar1=np.array([1,2,3,4,5,6])
print(ar1)

[1 2 3 4 5 6]


In [48]:
ar1

array([1, 2, 3, 4, 5, 6])

In [49]:
ar1=np.array(liste1)
print(ar1)

[1 2 3 4 5 6]


In [50]:
ar1=np.array([1,2,3,4,5,6])
print(ar1.ndim)

1


In [51]:
ar1=np.array([1,2,3,4,5,6],dtype=float)
print(ar1)

[1. 2. 3. 4. 5. 6.]


In [52]:
ar1=np.array([1,2,3,4,5,6],dtype=complex)
print(ar1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [53]:
print(type(ar1))

<class 'numpy.ndarray'>


In [54]:
print(ar1.dtype)

complex128


In [55]:
ar1=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11],[12,13,14]])
print(ar1)

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [56]:
print(ar1.ndim)

2


In [57]:
print(ar1.shape)  #(5 satır 3 sütun)(ilk dimension 5 2.3)

(5, 3)


In [58]:
print(ar1.reshape(3,5)) #son ve ilk sayıları çarpımları aynı değeri verecek(ilk dimension 3 element 2. 5 element)

[[ 1  2  3  4  5]
 [ 6  6  7  8  9]
 [10 11 12 13 14]]


In [59]:
print(ar1.reshape(1,15))

[[ 1  2  3  4  5  6  6  7  8  9 10 11 12 13 14]]


In [60]:
ar1=np.random.randint(10,50,15).reshape(3,5)
print(ar1)

[[34 22 48 41 25]
 [30 10 44 15 17]
 [15 29 13 34 27]]


In [61]:
ar=np.array([1,2,3,4,5,6])
print(ar)


[1 2 3 4 5 6]


In [62]:
ar3=np.arange(0,10,2)
print(ar3)

[0 2 4 6 8]


In [63]:
ar3=np.linspace(0,100,5)
print(ar3)

[  0.  25.  50.  75. 100.]


In [64]:
ar4=ar3.copy()
print(ar4)

[  0.  25.  50.  75. 100.]


In [65]:
ar5=np.random.random((3,2,5))
print(ar5)


[[[0.73758898 0.61351524 0.39443282 0.61807241 0.69285317]
  [0.55298885 0.6135175  0.44850111 0.08499985 0.90305573]]

 [[0.52309047 0.47606201 0.40288894 0.21698155 0.32945173]
  [0.47422353 0.45404499 0.92348646 0.39620928 0.19306866]]

 [[0.08270913 0.53902116 0.19980282 0.0859566  0.26459863]
  [0.6336487  0.27960619 0.01019432 0.52757109 0.80705972]]]


In [66]:
ar5=np.random.random((2,2))
print(ar5)


[[0.32138824 0.01504188]
 [0.94642225 0.07553648]]


In [67]:
ar5=np.random.random((2))
print(ar5)

[0.74349272 0.28061774]


In [68]:
ar5=np.random.rand(10)
ar6=np.random.randn(10)
print(ar5)
print(ar6)
#rand= 0 1 arası randn=-1 1 arası

[0.23209336 0.75052727 0.71707671 0.10418881 0.4462335  0.47610854
 0.92648472 0.08391427 0.48009547 0.23878103]
[ 0.52029834 -0.56826455  1.49594853 -0.03703095 -0.83480146  0.02418073
 -0.42010199 -0.94732733  1.0478953  -0.78178609]


In [69]:
ar6=np.random.randint(2,5,(3,3))#ilk 2 sayı aralık 3.shape
print(ar6)

[[2 2 2]
 [3 4 2]
 [3 3 2]]


In [70]:
ar6=np.random.randint(2,size=3)#0 la 2 arası şimdi aralık
print(ar6)

[1 0 1]


In [71]:
ar1=np.arange(1,11)
ar1=ar1.reshape(5,2)
print(ar1)
print(ar1[0])#satır/eleman(?)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[1 2]


In [72]:
 print(ar1[0:2])

[[1 2]
 [3 4]]


In [73]:
 print(ar1[0:4:2])

[[1 2]
 [5 6]]


In [74]:
print(ar1[0,:])#1.satır

[1 2]


In [75]:
print(ar1[:,1])#2.sütun

[ 2  4  6  8 10]


In [76]:
print(ar1[2,1])#2.satır 1. sütun

6


In [77]:
print(ar1[::-1])

[[ 9 10]
 [ 7  8]
 [ 5  6]
 [ 3  4]
 [ 1  2]]


In [78]:
ar1=np.zeros((6,3,5))#baştaki kaç tane olacağı 3 ve 5 iste satır sütün değerlerini gösteriyor

In [79]:
print(ar1)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [80]:
print(ar1.ndim)


3


In [81]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [82]:
np.random.normal(10,4,(3,5))#standart sapması 4 ort u 10 olan 3,5 shapeli dizi oluşturma

array([[11.91087878,  7.40104537,  9.20683904,  9.69851964,  8.90268905],
       [ 4.99592416, 11.78395146, 10.84019272, 11.67812698,  8.57127523],
       [18.73078055, 10.36147399, 15.14867379,  9.2415102 ,  5.32561378]])

In [83]:
ar1=np.ones((5,3,2))

In [84]:
print(ar1)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [85]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [86]:
ar1=np.array([[1,2,3],
            [4,5,6]])
ar2=np.array([[8,9,10],
            [10,11,22]])
print(np.concatenate([ar1,ar2]))
print(np.concatenate([ar1,ar2],axis=1))
print(np.concatenate([ar1,ar2],axis=0))#0 olursa altalta #1 olursa yanyana birleştiriyo

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [10 11 22]]
[[ 1  2  3  8  9 10]
 [ 4  5  6 10 11 22]]
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [10 11 22]]


In [87]:
ar1.max()

6

In [88]:
ar2.min()

8

In [89]:
ar3.argmax()#arg max veya min in indexini söyler

4

In [90]:
ar3.argmin()

0

In [91]:
ar1.sum()

21

In [92]:
satırların_top=ar1.sum(axis=1)
print(satırların_top)

[ 6 15]


In [93]:
sütunların_top=ar1.sum(axis=0)

In [94]:
print(sütunların_top)

[5 7 9]


In [95]:
ar1.mean()#ortalama

3.5

In [96]:
ar1.var()#varyans 

2.9166666666666665

In [97]:
ar1.std()#(standart sapma)  varyansın kökünü alınca geliyo

1.707825127659933

In [98]:
ar1=np.array([[1,2,3],
            [4,5,6]])
ar2=np.array([[8,9,10],
            [10,11,22]])
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar2/ar1)
print(ar2%ar1)
print(ar2//ar1)

[[ 9 11 13]
 [14 16 28]]
[[ -7  -7  -7]
 [ -6  -6 -16]]
[[  8  18  30]
 [ 40  55 132]]
[[8.         4.5        3.33333333]
 [2.5        2.2        3.66666667]]
[[0 1 1]
 [2 1 4]]
[[8 4 3]
 [2 2 3]]


In [99]:
print(ar1*2)#np.multiply(ar1,2)(add,substract,divide,power,mod,np.absolute(np.array([-3])))

[[ 2  4  6]
 [ 8 10 12]]


In [100]:
print(np.sin(ar1))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [101]:
print(np.sqrt(ar1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [102]:
print(np.exp(ar1))#e üzeri hesaplama

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [103]:
print(np.log(ar1))#10 tabanında log hesaplar (log3,log2...)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [104]:
ar1=np.array([[1,2,3],
            [4,5,6]])
ar2=np.array([[8,9],
            [10,11],[12,13]])
              
              
print(np.dot(ar1,ar2))#matris slk saçma çarpmalar

[[ 64  70]
 [154 169]]


In [105]:
print(ar1.T)#transpose satırlar, sütun sütunlar satır

[[1 4]
 [2 5]
 [3 6]]


In [106]:
print(ar1>3)

[[False False False]
 [ True  True  True]]


In [107]:
print(ar1[ar1>3])

[4 5 6]


In [108]:
np.save("save",ar1)

In [109]:
ar1=np.load("save.npy")