In [16]:
import numpy as np

In [17]:
v=np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [18]:
[v[9], v[0]]

[27, 0]

In [19]:
ind=[2,0,1]

In [20]:
v[ind]#bu indekslerle kendimiz yeni bi dizi oluşturabildik (fancy index)

array([6, 0, 3])

In [21]:
m=np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])


In [22]:
m[ind]#bu indekslerle kendimiz yeni bi dizi oluşturabildik (fancy index)

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [23]:
m[0, [1,2]]#bu indekslerle kendimiz yeni bi dizi oluşturabildik (fancy index)

array([1, 2])

In [24]:
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])

v[-2]

9

In [25]:

np.random.randint(10, size = (3,2,2))

array([[[9, 8],
        [6, 4]],

       [[7, 6],
        [9, 7]],

       [[9, 9],
        [7, 5]]])

In [26]:
a=np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])
a[2,3]#satır ve sütün indekslerini girerek dizi elemanını bulma

8

In [27]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [28]:
a=np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])
a[1,1]

5

In [29]:
a=np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])
a[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [30]:
v=np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

[v[1], v[3]]

[3, 9]

In [31]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])
a[:2,:3]#(satır ve sütun)#2li işlemlerde ilk hep satır 2.sütun

array([[4, 7, 4],
       [2, 5, 0]])

In [32]:
a[::,:2]#(satır ve sütun)

array([[4, 7],
       [2, 5],
       [1, 9]])

In [33]:
x = np.array([1, 2, 3])

y = np.array([4, 5, 6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [34]:
x.size

3

In [35]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])
a[:,2]

array([4, 0, 0])

In [36]:
x=np.array([1,2,3,99,99,3,2,1])

In [37]:
np.split(x,[3,5])#3.indeksten bi ayır sonra 5.indeksten bi ayır 

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [38]:
m=np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [39]:
np.split(m,[2])#(satır olarak)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
np.hsplit(m,[2])#(sütun olarak)(height split)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [41]:
a=np.array([2,3,1,4])


In [42]:
np.sort(a)

array([1, 2, 3, 4])

In [43]:
a

array([2, 3, 1, 4])

In [44]:
a.sort()

In [45]:
a

array([1, 2, 3, 4])

In [46]:
m=np.arange(16).reshape(4,4)
np.sort(m,axis=1)#satırda sıralama yapar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.sort(m,axis=0)#sütunda sıralama yapar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])